[package]
name = "scirs2-fft"
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["SciRS2 Team"]
description = "Fast Fourier Transform module for SciRS2"
license = "Apache-2.0"
repository = "https://github.com/cool-japan/scirs"
keywords = ["fft", "fourier", "scientific", "scipy", "numerical"]
categories = ["science", "mathematics", "algorithms"]

[features]
default = ["helper", "window", "parallel"]
helper = []
window = []
minimal = []
parallel = []

[dependencies]
# Core dependencies
ndarray = { version = "0.16.1", features = ["serde", "rayon"] }
num-traits = "0.2.19"
num-complex = "0.4.6"
thiserror = "1.0.69"
scirs2-core = { path = "../scirs2-core", version = "0.1.0-alpha.1", features = ["simd", "parallel"] }
rayon = "1.10.0"

# FFT specific dependencies
rustfft = "6.2.0"
rand = "0.9.0"

[dev-dependencies]
approx = "0.5.1"
criterion = "0.5.1"
