[package]
name = "scirs2-neural"
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["SciRS2 Team"]
license = "Apache-2.0"
description = "Neural network building blocks module for SciRS2"
repository = "https://github.com/cool-japan/scirs"
keywords = ["neural-network", "deep-learning", "scientific", "ai", "machine-learning"]
categories = ["science", "mathematics", "algorithms"]

[dependencies]
# Core dependencies
scirs2-core = { path = "../scirs2-core", version = "0.1.0-alpha.1", optional = true }
# Temporarily commented out for publishing
# scirs2-linalg = { path = "../scirs2-linalg", version = "0.1.0-alpha.1", optional = true }
# scirs2-optimize = { path = "../scirs2-optimize", version = "0.1.0-alpha.1", optional = true }
# scirs2-optim = { path = "../scirs2-optim", version = "0.1.0-alpha.1", optional = true }
ndarray = { version = "0.16.1", features = ["serde", "rayon"] }
ndarray-stats = "0.5.0"
num-integer = "0.1.46"
approx = "0.5.1"
num-traits = "0.2.19"
num-complex = "0.4.6"
thiserror = "1.0.69"
rand = "0.9.0"

# AI/ML specific dependencies
autograd = "1.1.1"
# Temporarily commented out for publishing
# scirs2-autograd = { path = "../scirs2-autograd", version = "0.1.0-alpha.1" }

# Future dependency for PandRS and NumRS with appropriate abstractions
# pandrs_wrapper = { path = "../wrappers/pandrs_wrapper", optional = true }
# numrs_wrapper = { path = "../wrappers/numrs_wrapper", optional = true }

[features]
default = []
full = ["core"]  # Temporarily limited for publishing
core = ["dep:scirs2-core"]
# Features temporarily disabled for publishing
# linalg = ["dep:scirs2-linalg"] 
# optimize = ["dep:scirs2-optimize"]
optim = [] # Empty feature for compatibility with existing code

[[example]]
name = "autograd_example"
path = "examples/autograd_example.rs"