# Build optimization configuration for faster compilation

[build]
# Use fewer jobs in CI to reduce memory usage
jobs = 2
rustflags = [
    "-C", "link-arg=-lopenblas",
    "-C", "target-cpu=native",
    "-C", "debuginfo=1",
    "-C", "link-arg=-Wl,--compress-debug-sections=zlib",
    "-C", "link-arg=-Wl,--gc-sections",
]

[target.x86_64-unknown-linux-gnu]
# Use faster linker for Linux builds with CI optimizations
rustflags = [
    "-C", "link-arg=-lopenblas",
    "-C", "target-cpu=native",
    "-C", "debuginfo=1",
    "-C", "link-arg=-Wl,--compress-debug-sections=zlib",
    "-C", "link-arg=-Wl,--gc-sections",
]

# Cargo configuration for development speed
[cargo-new]
vcs = "none"  # Skip git init for new crates

[term]
verbose = false  # Reduce output verbosity

# Profile optimizations for dev builds  
[profile.dev]
debug = 1        # Reduced debug info for faster compilation
opt-level = 0    # No optimization for fastest compilation
incremental = false  # Disable incremental compilation in CI
overflow-checks = true

# CI-optimized profile for space-constrained environments
[profile.ci]
inherits = "dev"
debug = 1
opt-level = 0
lto = false
codegen-units = 16
incremental = false

# Optimized dev profile for testing
[profile.test]
debug = 1
opt-level = 1    # Minimal optimization for tests
incremental = true

[profile.release]
# Production optimization settings
debug = false
opt-level = 3
lto = "thin"     # Thin LTO for good performance with reasonable compile times
codegen-units = 1
panic = "abort"
strip = true     # Strip symbols to reduce binary size

# Benchmark profile
[profile.bench]
debug = false
opt-level = 3
lto = "thin"
codegen-units = 1