[package]
name = "scirs2-interpolate"
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["SciRS2 Team"]
description = "Interpolation module for SciRS2"
license = "Apache-2.0"
repository = "https://github.com/cool-japan/scirs"
keywords = ["interpolation", "spline", "scientific", "scipy", "numerical"]
categories = ["science", "mathematics", "algorithms"]

[dependencies]
# Core dependencies
scirs2-core = { path = "../scirs2-core", version = "0.1.0-alpha.1" }
scirs2-linalg = { path = "../scirs2-linalg", version = "0.1.0-alpha.1" }
ndarray = { version = "0.16.1", features = ["serde", "rayon"] }
num-traits = "0.2.19"
num-complex = "0.4.6"
thiserror = "2.0.12"

[dev-dependencies]
approx = "0.5.1"
criterion = "0.5.1"

[features]
default = []
