[package]
name = "scirs2-series"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Time series analysis module for SciRS2 (scirs2-series)"
license.workspace = true
repository.workspace = true
keywords = ["time-series", "forecasting", "scientific", "ai", "machine-learning"]
categories = ["science", "mathematics", "algorithms"]

[dependencies]
# Core dependencies
scirs2-core = { workspace = true, features = ["linalg"] }
# Temporarily commented out for publishing
# scirs2-stats = { workspace = true }
# scirs2-fft = { workspace = true }
ndarray = { workspace = true }
# BLAS dependencies removed - using core abstractions
# ndarray-linalg = { workspace = true, features = ["openblas-system"] }
# openblas-src = { workspace = true }
num-traits = { workspace = true }
num-complex = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }

# Future dependency for PandRS with appropriate abstractions
# pandrs_wrapper = { path = "../wrappers/pandrs_wrapper", optional = true }

[dev-dependencies]
approx = { workspace = true }

[features]
default = []
# Enable external ML library wrappers
# pandrs = ["dep:pandrs_wrapper"]
