name: SciRS2 CI

on:
  push:
    branches: [ "main", "master", "feature/*" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  CARGO_TERM_COLOR: always
  # Reduce parallel jobs to save memory and disk space
  CARGO_BUILD_JOBS: 2
  # Disable incremental compilation to save ~1-2GB
  CARGO_INCREMENTAL: 0
  # Reduce debug info size
  CARGO_PROFILE_DEV_DEBUG: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Free up ~14GB of system disk space
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker system prune -af
          df -h
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: "Install cargo nextest"
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libopenblas-dev pkg-config libfreetype6-dev libfontconfig1-dev

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      
      - name: Run tests
        run: cargo nextest run --verbose
